### ISSUE TITLE
documentation has some holes

### ISSUE THREAD

**Issue by jeffhammond** [pacxx/pacxx-llvm#2]
I am trying to following the docs to get the example code working.

First, I don't think it is user-friendly to require users to implement a CMake build system just to compile a single source test program.  This dramatically increases the barrier to entry.

Second, the CMake-based documentation is incomplete.  Doing so leads to an error about missing `FindPACXX.cmake`.  I tried to put it in the right place, but it doesn't fix the problem.  Details below.

In short, if developing CMake buildsystems from scratch - even apparently trivial ones - is a pre-requisite for using PACXX, then I won't use it.  No competition project such as Boost.Compute or SYCL has such a requirement.

```
jrhammon@klondike:~/prk-repo/Cxx11/pacxx-test/build$ CC=/opt/llvm/pacxx/bin/clang CXX=/opt/llvm/pacxx/bin/clang++ cmake .. -DPACXX_DIR=/opt/llvm/pacxx/ -DCMAKE_MODULE_PATH=/home/jrhammon/prk-repo/Cxx11/pacxx-test
-- The C compiler identification is Clang 7.0.0
-- The CXX compiler identification is Clang 7.0.0
-- Check for working C compiler: /opt/llvm/pacxx/bin/clang
-- Check for working C compiler: /opt/llvm/pacxx/bin/clang -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /opt/llvm/pacxx/bin/clang++
-- Check for working CXX compiler: /opt/llvm/pacxx/bin/clang++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at CMakeLists.txt:6 (find_package):
  By not providing "FindPACXX.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "PACXX", but
  CMake did not find one.

  Could not find a package configuration file provided by "PACXX" with any of
  the following names:

    PACXXConfig.cmake
    pacxx-config.cmake

  Add the installation prefix of "PACXX" to CMAKE_PREFIX_PATH or set
  "PACXX_DIR" to a directory containing one of the above files.  If "PACXX"
  provides a separate development package or SDK, be sure it has been
  installed.


-- Configuring incomplete, errors occurred!
See also "/home/jrhammon/prk-repo/Cxx11/pacxx-test/build/CMakeFiles/CMakeOutput.log".
jrhammon@klondike:~/prk-repo/Cxx11/pacxx-test/build$ ll ..
total 28K
drwxrwxr-x 3 jrhammon jrhammon 4.0K Feb  5 10:34 build
-rw-rw-r-- 1 jrhammon jrhammon  442 Feb  5 10:25 CMakeLists.txt
-rw-rw-r-- 1 jrhammon jrhammon  101 Feb  5 10:26 compile
-rw-rw-r-- 1 jrhammon jrhammon 9.3K Feb  5 10:27 FindPACXX.cmake
-rw-rw-r-- 1 jrhammon jrhammon 1.5K Feb  5 10:24 test.cc
```

**Comment by pacxx** [comment]
Hi Jeff thanks for your efforts to test PACXX. 

I will updated the CMake instructions in the next days. 

In the mean time, with https://github.com/pacxx/pacxx-llvm/commit/65cf8a1857e4a75a605bb2b536f9a189d4b5a150 I added a compiler driver to PACXX. 
It is a python (2.7) script that can be used as a replacement of clang to compile PACXX programs. 
You should not need any custom python packages to run it.

With the driver sould be able to compile a simple example with: 
`pacxx++ vector_add.cpp -o vector_add`
The script will perform equal steps to the CMake integration. Moreover, you can also use it as CXX compiler in a CMake projekt without calling the find_package(PACXX) cmake function. The driver brings everything you need. 

Please provide some feedback how and if it works.

**Comment by jeffhammond** [comment]
Thanks!

Everything is working now, with one minor caveat.  The Python script fails with Python 3 but not Python 2.  I do not know Python well enough to debug this, and the workaround is simple enough.

```
/opt/llvm/pacxx/bin/pacxx++ -std=c++14 -DPRKVERSION="2.16" nstream-pacxx.cc -DUSE_PACXX -DUSE_BOOST -I/usr/local -o nstream-pacxx
Traceback (most recent call last):
  File "/opt/llvm/pacxx/bin/pacxx++", line 177, in <module>
    main(sys.argv)
  File "/opt/llvm/pacxx/bin/pacxx++", line 169, in main
    ctx = Context()
  File "/opt/llvm/pacxx/bin/pacxx++", line 66, in __init__
    self.llvm_config()
  File "/opt/llvm/pacxx/bin/pacxx++", line 76, in llvm_config
    self.llvm_libs= check_output([self.pacxx_dir + "/llvm-config", "--libs"]).rstrip().split(" ")
TypeError: a bytes-like object is required, not 'str'
Makefile:135: recipe for target 'nstream-pacxx' failed
make: *** [nstream-pacxx] Error 1
```
