### ISSUE TITLE
rpath in compiler script

### ISSUE THREAD

**Issue by jeffhammond** [pacxx/pacxx-llvm#4]
Adding `rpath` to the compiler script means that the user does not have modify `LD_LIBRARY_PATH` for programs to run.  This is convenient if one wants to have both PACXX and a potentially incompatible non-PACXX LLVM toolchain active in the same environment.

The patch is trivial.  I think it looks like this, but I don't know if you have to do something different for Windows.
```python
    def insert_libdir(self, path, suffix):
        if path:
            self.libs.append("-L")
            self.libs.append(path+"/lib"+(suffix or ''))
            self.libs.append("-Wl,-rpath")
            self.libs.append("-Wl,"+path+"/lib")
```

**Comment by pacxx** [comment]
Added in last commit. Thanks!
